# ---------- Stage 1: Builder ----------
FROM python:3.12-alpine AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /usr/src/core

RUN apk add --no-cache \
    build-base \
    libpq-dev

COPY ./requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY ./core .

# ---------- Stage 2: Runtime ----------
FROM python:3.12-alpine AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /usr/src/core

RUN apk add --no-cache \
    bash \
    netcat-openbsd \
    libpq-dev  # چون alembic ممکنه به PostgreSQL نیاز داشته باشه

# فقط پکیج‌های نصب‌شده و کد رو کپی کن
COPY --from=builder /usr/lib/python3.12/site-packages /usr/lib/python3.12/site-packages
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/src/core .

COPY ./entrypoint.sh /usr/src/core/entrypoint.sh
RUN chmod +x /usr/src/core/entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/usr/src/core/entrypoint.sh"]
