
FROM python:3.12-slim

WORKDIR /usr/src/core

COPY ./requirements.txt .

# RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

# using mirror:
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./core .

# CMD ["fastapi", "run","--host","0.0.0.0","--port","80"]

COPY ./entrypoint.sh /usr/src/core/entrypoint.sh
RUN chmod +x /usr/src/core/entrypoint.sh

ENTRYPOINT ["/usr/src/core/entrypoint.sh"]
EXPOSE 80